spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  application:
    name: gulimall-search
  redis:
    host: 192.168.0.102
    port: 6379
  session:
    store-type=redis

server:
  port: 12000

logging:
  level:
    com.atguigu.gulimall: debug